# Configuration for a default project
Directories:
  Database:
    Purpose: Binary (float32) timeseries arrays and corresponding posix timemstamp (float64) in a subdirectory structure that partitions data by Year, siteID, and cleaning stage
    Structure: YYYY/siteID/stage
    Metadata:
      Data_traces:
        dtype: float32
        precision: 4
      POSIX_timestamp:
        dtype: float64
        precision: 8
        base_unit: s
      Time_resolution: 30min
  rawData:
    Purpose: Source files for the project, stored by with an inventory to track whether files have been dumped to the database.  Contents are organized by siteID, Type, Year, and Month, if timestamps are can be parsed from the filename or just siteID and Type if no time information available.
  config_files:
    Purpose: Configuration files
Processing:
  firstStage:
  # Template for the first stage of the pipeline, which reads from the rawData folder and writes to the Database folder.  
  # No data-based cleaning. Writes all data in a standardized format with evenly spaced intervals
    defaultVariable:
      unit: 
      dataType: float32
      import: True
      

